<?php

/**
 * @file
 * Defines a CCK field for source code with GeSHi syntax highlighting.
 *
 * @todo: is the GeSHi CSS file always loaded when needed?
 */

use Drupal\geshifilter\GeshiFilterProcess;

/**
 * Implements hook_theme().
 */
function geshifield_theme() {
  return [
    'geshifield_default' => [
      'render element' => 'geshifield',
      'variables' => [
        'language' => NULL,
        'sourcecode' => NULL,
      ],
    ],
  ];
}

/**
 * Format the field.
 *
 * This function get the sorcecode and language and format it using geshi.
 *
 * @param array $variables
 *   Variables disponible for theme.
 *
 * @return string
 *   The HTML to show the code formated with geshi.
 */
function template_preprocess_geshifield_default(&$variables) {
  $language = $variables['language'];
  $sourcecode = $variables['sourcecode'];
  $variables['geshicode'] = GeshiFilterProcess::geshiProcess($sourcecode, $language);
}
