<?php

/**
 * @file
 * Contains advupdate.module.
 */

use Drupal\advupdate\Render\UpdateDetailsMarkup;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function advupdate_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the advupdate module.
    case 'help.page.advupdate':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The module modifies the Drupal "Updates available" email to include the information normally shown at /admin/reports/updates/update, with links to the module updates and their release notes.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function advupdate_form_update_settings_alter(&$form, FormStateInterface $form_state, $form_id) {
  $advupdate_config = \Drupal::config('advupdate.settings');

  $form['update_notification_extend_email_report'] = [
    '#type' => 'checkbox',
    '#title' => t('Expand the report using "Update Manager Advanced" module'),
    '#default_value' => $advupdate_config->get('notification.extend_email_report'),
    '#description' => t('An email will include more detailed information with a list of modules.'),
  ];

  $form['#submit'][] = 'advupdate_form_update_settings_submit_handler';
}

/**
 * Save "notification.extend_email_report" to the configuration.
 */
function advupdate_form_update_settings_submit_handler($form, FormStateInterface $form_state) {
  \Drupal::configFactory()->getEditable('advupdate.settings')
    ->set('notification.extend_email_report', $form_state->getValue('update_notification_extend_email_report'))
    ->save();
}

/**
 * Implements hook_mail_alter().
 */
function advupdate_mail_alter(&$message) {
  if ($message['id'] == 'update_status_notify'
    && \Drupal::config('advupdate.settings')
      ->get('notification.extend_email_report') == 1) {
    if ($additional_data = _advupdate_mail_additional_data()) {
      $message['body'][] = "";
      $message['body'][] = $additional_data;
      $message['body'][] =
        t('This emails also may contain additional information added by the "Update Manager Advanced" module (:url).', [
          ':url' => Url::fromUri('https://www.drupal.org/project/advupdate', ['absolute' => TRUE])
            ->toString(),
        ]);
    }
  }
}

/**
 * Render a list for available updating of core/modules/themes.
 */
function _advupdate_mail_additional_data() {
  \Drupal::moduleHandler()->loadInclude('update', 'module');
  \Drupal::moduleHandler()->loadInclude('update', 'inc', 'update.compare');

  $available = update_get_available(FALSE);
  if (empty($available)) {
    return FALSE;
  }

  $project_data = update_calculate_project_data($available);
  return UpdateDetailsMarkup::createFromProjectData($project_data);
}
