_core:
  default_config_hash: cLPUKXMlBdHBqZyzVRCLdj0IK7Z5zD6ro3GLAuIpiNU
disqus_domain: easy-drupal
behavior:
  disqus_localization: false
  disqus_inherit_login: false
  disqus_track_newcomment_ga: true
  disqus_notify_newcomment: false
  disqus_disable_mobile: false
  disqus_lazy_load: 1
  disqus_count_js: 0
advanced:
  disqus_useraccesstoken: 53a804fb22f14356947208f4e35e59b8
  disqus_publickey: uf0Mbq1NoMdzMIbqsgDqoAV9pe910S93ngpPZV6MyQVyT51d8d6vFgDe8mE2muI8
  disqus_secretkey: zi6OOx2TsZr3zdK1WuyhqAhVwjA9aMu9rHCemo5qgMTEImtZCz4Ab6dSgs4h8jnE
  api:
    disqus_api_update: false
    disqus_api_delete: '0'
  sso:
    disqus_sso: true
    disqus_use_site_logo: false
    disqus_logo: ''
