_core:
  default_config_hash: Nu7A-_9XQJ6mwtc1Dfm0ua3mSFoWzG-pC-xEL-SejjA
settings:
  library_url: 'https://cdnjs.cloudflare.com/ajax/libs/cropper/2.1.0/cropper.min.js'
  css_url: 'https://cdnjs.cloudflare.com/ajax/libs/cropper/2.1.0/cropper.min.css'
  crop_preview_image_style: crop_thumbnail
  crop_list: {  }
  warn_multiple_usages: true
  show_default_crop: true
  show_crop_area: false
  notify_apply: false
  notify_update: true
