channels:
  -
    id: purgers
    grants:
      - 0
      - 2
      - 3
  -
    id: queue
    grants:
      - 0
      - 2
      - 3
  -
    id: diagnostics
    grants:
      - 3
  -
    id: purger_http_50eb80a982
    grants:
      - 0
      - 2
      - 3
