_core:
  default_config_hash: vFARRSP9-YgEArfDNYmRSg0cNFOgZPxqziffIalgLbU
max_links: 2000
cron_generate: true
cron_generate_interval: 24
remove_duplicates: true
skip_untranslated: false
base_url: 'https://makedrupaleasy.com'
default_variant: default
custom_links_include_images: false
excluded_languages: {  }
enabled_entity_types:
  - node
  - taxonomy_term
  - menu_link_content
entities_per_queue_item: 50
