# Schema for the configuration files of the disqus module.

disqus.settings:
  type: config_object
  label: 'Disqus Settings'
  mapping:
    disqus_domain:
      type: text
      label: 'Shortname'
    behavior:
      type: mapping
      label: 'Behavior'
      mapping:
        disqus_localization:
          type: boolean
          label: 'Localization support'
        disqus_inherit_login:
          type: boolean
          label: 'Inherit User Credentials'
        disqus_track_newcomment_ga:
          type: boolean
          label: 'Track new comments in Google Analytics'
        disqus_notify_newcomment:
          type: boolean
          label: 'Notify of new comments by email'
    advanced:
      type: mapping
      label: 'Advanced'
      mapping:
        disqus_useraccesstoken:
          type: text
          label: 'User Access Token'
        disqus_publickey:
          type: text
          label: 'Public Key'
        disqus_secretkey:
          type: text
          label: 'Secret Key'
        api:
          type: mapping
          label: 'Disqus API Settings'
          mapping:
            disqus_api_update:
              type: boolean
              label: 'Update Threads'
            disqus_api_delete:
              type: string
              label: 'Close/Remove Thread'
        sso:
          type: mapping
          label: 'Single Sign-On'
          mapping:
            disqus_sso:
              type: boolean
              label: 'Use Single Sign-On'
            disqus_use_site_logo:
              type: boolean
              label: 'Use Site Logo'
            disqus_logo:
              type: uri
              label: 'Custom Logo'

field.value.disqus_comment:
  type: mapping
  label: 'Disqus field values'
  mapping:
    status:
      type: boolean
      label: 'Disqus comments should be shown'
    identifier:
      type: string
      label: 'Identifier of the Disqus discussion'
