<?php
/**
 * @file
 * Contains schema_metatag_extensions.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function schema_metatag_extensions_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.schema_metatag_extensions':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Allow to add an additional data to JSON provided by "Schema.org Metatag" module.') . '</p>';
      return $output;

    default:
  }
}
