<?php
/**
 * @file
 * Contains easydrupal_common.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function easydrupal_common_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.easydrupal_common':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Setting the common functionality of the site.') . '</p>';
      return $output;

    default:
  }
}
