name: 'Configuration Partial Export'
type: module
core_version_requirement: '^9 || ^10 || ^11'
description: 'Partial export of selected configuration files.'
package: Development
dependencies:
  - drupal:config
tags:
  - developer
