name: Configuration Partial Export
type: module
description: Partial export of selected configuration files.
core_version_requirement: ^9 || ^10
package: Development
dependencies:
  - drupal:config
tags:
  - developer

# Information added by Drupal.org packaging script on 2023-03-20
version: '2.0.0-alpha1'
project: 'config_partial_export'
datestamp: 1679347688
